name: push_workflow
on: [push, pull_request]
jobs:
  web-app-tes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: web-app Unit Tests
        run: |
          cd web-app
          npm install -g npm@latest
          npm install -g @angular/cli@latest
          npm --version
          ng version
          npm install
          ng test --no-watch --no-progress --browsers=ChromeHeadlessCI