name: push_workflow
on: [push, pull_request]
jobs:
  web-app-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm version
        run: |
          npm install npm -g
          npm --version
          npm install @angular/cli -g
      - name: install packages
        run: |
          cd web-app
          npm install
          ng version
      - name: run tests
        run: |
          cd web-app
          ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
  web-app-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm version
        run: |
          npm install npm -g
          npm --version
          npm install @angular/cli -g
      - name: install packages
        run: |
          cd web-app
          npm install
          ng version
      - name: run tests
        run: |
          cd web-app
          ng build
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest ./helper