name: push_workflow
on: [push, pull_request]
jobs:
  web-app-tes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update npm
        run: |
          npm install -g npm@latest
          npm --version
      - name: install packages
        run: |
          cd web-app
          npm install
          npm --version
          ng version
      - name: run tests
        run: |
          cd web-app
          ng test --no-watch --no-progress --browsers=ChromeHeadlessCI